### ISSUE TITLE
アイテム選択行数の6行目以降が表示されません

### ISSUE THREAD

**Issue by tsuk46** [ArtemisJP/RPGMZ-ARTM_TMEventItemExMz#3]
アイテム選択画面において表示行数を5行以上に増やしたとき、6行目以降が選択可能にも関わらず表示されない状態になります。
この現象は新規プロジェクトでも発生します。
プラグインのバージョンは1.1.0、ツクールのバージョンは1.7.0です。
![WS000248](https://github.com/ArtemisJP/RPGMZ-ARTM_TMEventItemExMz/assets/153512154/c90af3e7-6f4a-4924-a1f1-e6e1496139e6)

**Comment by ArtemisJP** [comment]
再現を確認致しました。
お時間いただく形となりますが、対応予定です

**Comment by tsuk46** [comment]
修正が確認できました！
ご対応、誠にありがとうございます！
おかげさまで助かりました。
